import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const owner='11111111-1111-4111-8111-111111111111',reader='22222222-2222-4222-8222-222222222222';
await db.exec(`create schema auth;create table auth.users(id uuid primary key,email text,password_marker text);create role anon;create role authenticated;grant usage on schema public,auth to authenticated,anon;create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
insert into auth.users values('${owner}','santi.achar@gmail.com','existing-password'),('${reader}','reader@example.test','reader-password');`);
await db.exec(await readFile(new URL('../../../supabase/migrations/202609070001_orders.sql',import.meta.url),'utf8'));
await db.query('insert into public.erp_members(user_id) values($1)',[owner]);
await db.exec(await readFile(new URL('../../../supabase/migrations/202609100001_personnel_access.sql',import.meta.url),'utf8'));
assert.equal((await db.query('select password_marker from auth.users where id=$1',[owner])).rows[0].password_marker,'existing-password');
const login=async id=>db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${id}';`);
const access=async(email,enabled,admin,permissions,version=null)=>db.query('select public.erp_set_access($1,$2,$3,$4,$5)',[email,enabled,admin,permissions,version]);
const employee={employeeNumber:'leg-1',documentNumber:'30.123.456',firstName:'Ana',lastName:'Pérez',hireDate:'2026-09-10',isActive:true,email:'',phone:'',address:'',department:'Planta',position:'Operaria',notes:''};
const save=async(payload,id=null,version=null)=>(await db.query('select * from public.erp_save_employee($1,$2,$3)',[id,version,JSON.stringify(payload)])).rows[0];
await login(owner);
assert.equal((await db.query('select public.erp_is_admin() ok')).rows[0].ok,true);
await access('reader@example.test',true,false,['personal:view']);
const record=await save(employee);assert.equal(record.employee_number,'LEG-1');assert.equal(record.document_number,'30123456');
await assert.rejects(save({...employee,employeeNumber:'leg-2'}));
await assert.rejects(save({...employee,documentNumber:'30123457'}));
await assert.rejects(save({...employee,hireDate:'2026-02-30'}));
await assert.rejects(save({...employee,firstName:' '}));
const edited=await save({...employee,isActive:false},record.id,1);assert.equal(edited.version,2);assert.equal(edited.payload.isActive,false);
await assert.rejects(save(employee,record.id,1));
await assert.rejects(access('santi.achar@gmail.com',false,true,[],1));
await login(reader);
assert.equal((await db.query('select * from public.erp_employees')).rows.length,1);
await assert.rejects(save(employee));
await assert.rejects(db.query('update public.erp_members set is_admin=true where user_id=$1',[reader]));
await assert.rejects(db.query('select * from public.erp_list_members()'));
await assert.rejects(access('reader@example.test',true,true,[],1));
await assert.rejects(db.query('update public.erp_employees set version=99'));
assert.equal((await db.query('select * from public.erp_orders')).rows.length,0);
const order={cliente:'Cliente',transporte:'Camión',fechaPedido:'2026-09-10',fechaEntrega:'2026-09-11',estado:'BORRADOR',items:[{id:'33333333-3333-4333-8333-333333333333',articulo:'Producto',cantidad:10,unidad:'L'}]};
await assert.rejects(db.query('select public.erp_save_order(null,null,$1)',[JSON.stringify(order)]));
await login(owner);
await access('reader@example.test',true,false,['personal:view','personal:manage','pedidos:view'],1);
await assert.rejects(access('reader@example.test',true,false,[],1));
await login(reader);
await save({...employee,employeeNumber:'leg-2',documentNumber:'30123457'});
await assert.rejects(db.query('select public.erp_save_order(null,null,$1)',[JSON.stringify(order)]));
await login(owner);await access('reader@example.test',false,false,[],2);
await login(reader);
assert.equal((await db.query('select * from public.erp_employees')).rows.length,0);
await assert.rejects(save(employee));
await login(owner);
assert.equal((await db.query('select * from public.erp_access_events')).rows.length,3);
await assert.rejects(access('reader@example.test',true,false,['personal:manage'],3));
await assert.rejects(access('missing@example.test',true,false,[]));
await db.exec('reset role;set role anon;');await assert.rejects(db.query('select * from public.erp_employees'));
await assert.rejects(db.query('select public.erp_is_admin()'));
await db.close();
console.log('PASS: preserved account, employee CRUD, duplicates, dates, stale edits, RLS, admin controls, grant/revoke, last admin and order RPC denial.');
