import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const uid='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222', itemId='33333333-3333-4333-8333-333333333333';
await db.exec(`create schema auth; create table auth.users(id uuid primary key); create role anon; create role authenticated; grant usage on schema public,auth to authenticated,anon; create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; insert into auth.users values ('${uid}'),('${other}');`);
await db.exec(await readFile(new URL('../../../supabase/migrations/202609070001_orders.sql',import.meta.url),'utf8'));
await db.query('insert into public.erp_members(user_id) values ($1)',[uid]);
await db.exec(`set role authenticated; set request.jwt.claim.sub='${uid}';`);
const payload={cliente:'Cliente prueba',transporte:'Transporte',fechaPedido:'2026-09-07',fechaEntrega:'2026-09-08',estado:'BORRADOR',items:[{id:itemId,articulo:'Producto',cantidad:10,unidad:'L'}]};
const save=async(p,id=null,version=null)=>(await db.query('select public.erp_save_order($1,$2,$3) id',[id,version,JSON.stringify(p)])).rows[0].id;
const issue=async(id,version,qty,confirm=true)=>(await db.query('select public.erp_issue_note($1,$2,$3,$4,$5) id',[id,version,JSON.stringify([{id:itemId,cantidad:qty}]),'2026-09-08',confirm])).rows[0].id;
const order=async(id)=>(await db.query('select * from public.erp_orders where id=$1',[id])).rows[0];
const id=await save(payload);
await assert.rejects(issue(id,1,2));
await save({...payload,estado:'CONFIRMADO'},id,1);
await assert.rejects(issue(id,2,4,false));
await issue(id,2,4);assert.equal((await order(id)).payload.estado,'PARCIAL');
await assert.rejects(issue(id,2,4));await assert.rejects(issue(id,3,7));
await assert.rejects(save({...payload,estado:'PARCIAL',items:[{...payload.items[0],cantidad:3}]},id,3));
await assert.rejects(save({...payload,estado:'PARCIAL',cliente:'Otro'},id,3));
await issue(id,3,6);assert.equal((await order(id)).payload.estado,'DESPACHADO');
assert.equal((await db.query('select count(*)::int n from public.erp_delivery_notes where order_id=$1',[id])).rows[0].n,2);
await assert.rejects(save({...payload,estado:'CANCELADO'},id,4));
const cancelled=await save({...payload,estado:'CONFIRMADO'});await issue(cancelled,1,3);await save({...payload,estado:'CANCELADO'},cancelled,2);await assert.rejects(issue(cancelled,3,1));
// Direct writes cannot bypass RPC rules or rewrite issued documents.
await assert.rejects(db.query('update public.erp_orders set version=99 where id=$1',[id]));
await assert.rejects(db.query('delete from public.erp_delivery_notes where order_id=$1',[id]));
await assert.rejects(db.query('insert into public.erp_members(user_id) values ($1)',[other]));
await db.exec(`set request.jwt.claim.sub='${other}'`);
assert.equal((await db.query('select * from public.erp_orders')).rows.length,0);
assert.equal((await db.query('select * from public.erp_delivery_notes')).rows.length,0);
assert.equal((await db.query('select * from public.erp_order_events')).rows.length,0);
await assert.rejects(save(payload));await assert.rejects(issue(id,4,1));
await db.exec(`reset role; update public.erp_members set enabled=false; set role authenticated; set request.jwt.claim.sub='${uid}'`);
assert.equal((await db.query('select * from public.erp_orders')).rows.length,0);await assert.rejects(save(payload));
await db.exec('reset role; set role anon;');
await assert.rejects(db.query('select * from public.erp_orders'));await assert.rejects(save(payload));
await db.close();
console.log('PASS: partial/full delivery, manual confirmation, stale retries, quantity validation, cancellation, RLS membership and anonymous/direct write rejection');
